### ISSUE TITLE
Java plugin doesn't run with rules_kotlin 1.6.0-RC.1

### ISSUE THREAD

**Issue by pswaminathan** [bazelbuild/rules_kotlin#743]
Example [here](https://github.com/pswaminathan/bazel-kt-databinding-crash/pull/8). `main` of this repository compiles. When switching to 1.6.0-RC-1, the build fails:

```
$ bazel build //app:app_lib
DEBUG: /private/var/tmp/_bazel_p/a48d838470da09ddcc3c8b96c3b3efad/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl:104:10: kt_jvm_library should be loaded from //kotlin:jvm.bzl
DEBUG: /private/var/tmp/_bazel_p/a48d838470da09ddcc3c8b96c3b3efad/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl:104:10: kt_jvm_library should be loaded from //kotlin:jvm.bzl
DEBUG: /private/var/tmp/_bazel_p/a48d838470da09ddcc3c8b96c3b3efad/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl:104:10: kt_jvm_library should be loaded from //kotlin:jvm.bzl
INFO: Analyzed target //app:app_lib (10 packages loaded, 270 targets configured).
INFO: Found 1 target...
ERROR: /Users/p/Code/examples/bazel-kt-databinding-crash/app/BUILD:7:22: KotlinKapt //app:app_lib-kotlin { kt: 9, java: 0, srcjars: 1 } for darwin_arm64 failed: (Exit 1): build failed: error executing command bazel-out/host/bin/external/io_bazel_rules_kotlin/src/main/kotlin/build '--flagfile=bazel-out/darwin_arm64-fastbuild/bin/app/app_lib-kotlin-kapt-gensrc.jar-0.params'
app/src/main/java/com/example/databinding/Api.kt:5:19: error: unresolved reference: UpdatesJsonAdapter
fun dealWith(uja: UpdatesJsonAdapter) {}
                  ^
May 09, 2022 3:08:37 PM worker request 0
SEVERE: Compilation failure: compile phase failed:Target //app:app_lib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 7.309s, Critical Path: 5.09s
INFO: 8 processes: 2 internal, 3 darwin-sandbox, 3 worker.
FAILED: Build did NOT complete successfully
```

This `UpdatesJsonAdapter` is built with [moshi-kotlin-codegen](https://github.com/pswaminathan/bazel-kt-databinding-crash/blob/main/third_party/moshi-kotlin-codegen/BUILD.bazel) plugin. This runs and builds correctly with v1.5.0, but not 1.6.0-RC-1.

**Comment by Bencodes** [comment]
@pswaminathan I'm unable to reproduce this if I update your demo to `com.squareup.moshi:moshi-kotlin-codegen:1.13.0` instead of `1.12.x`, and reference the apt processor class in the java plugin.

```Python
java_plugin(
    name = "moshi-kotlin-codegen-plugin",
    processor_class = "com.squareup.moshi.kotlin.codegen.apt.JsonClassCodegenProcessor",
    ...
)
```

**Comment by pswaminathan** [comment]
Yes, looks like this is an incompatibility in the library with 1.6. My apologies, and thanks for giving it a look! That sample app is basically a sanitized example of a production app I'm trying to migrate and was having some trouble with, and looks like this was a red herring. Upgrading the library version made it work.
