### ISSUE TITLE
Targets can get out of date

### ISSUE THREAD

**Issue by Kernald** [bazelbuild/rules_kotlin#531]
I'm not 100% sure of when or why it happens, and can't consistently reproduce it, but using the rules at 8d987688eb74d025d24106fbbfba57d8aa5e48dc sometimes results in targets being used without being recompiled. One example I encountered:

Target A depends on B. B contains a sealed class, with a simple list of sub-objects. A has a `when` statement on an instance of this sealed class. I add a subclass to this sealed class hierarchy in B, and update the `when` statement in A. IntelliJ is happily claiming that everything is fine - as intended. Running a bazel build or bazel test, on the other hand, will result in a compilation error in A's `when` statement, as according to the compiler, the new subclass doesn't exist. Changing B's implementation from there doesn't do anything - I have to run `bazel clean` to discard the faulty cache (I assume that's what's happening).

I just encountered it again and sadly ran `bazel clean` before thinking of investigating it a bit more in depth, next time it happens I'll try running a `bazel build //:B` and see if Bazel claims it's up-to-date, despite having changes, and inspect the jar as well, but I've definitely encountered this a few times since updating to 8d987688eb74d025d24106fbbfba57d8aa5e48dc (from the prebuilt v1.5.0-alpha-3).

**Comment by Kernald** [comment]
Update on this, which I just encountered again: `bazel build //:B` claims that the target is up-to-date which, looking at the content of the jar, seems correct. But for some reason, that jar is _not_ used to build A.

**Comment by Bencodes** [comment]
We just encountered something very similar in our repo. Same setup where target A depends on and references Kotlin sources in target B. Renaming a class (say `Foo.kt` to `Bar.kt`) in module B will result in a compilation failure due to target A not being able to reference `Bar.kt` despite that file existing.

**Comment by Bencodes** [comment]
This looks related https://github.com/bazelbuild/bazel/issues/13135

**Comment by mgenov** [comment]
Similar issue on my side. bazel clean needs to be executed to enforce using of the new jar.

**Comment by rockwotj** [comment]
We also hit this only when we're using persistent workers - does this happen without persistent workers? Additionally a bazel shutdown seems to fix things, instead of a bazel clean. It seems like the worker gets into a n invalid state or something... Is this the case for others? If not I can open a new issue to track

**Comment by cgruber** [comment]
@restingbull - I wonder if the multiplex worker is having an issue with cleaning up or isolating state?

**Comment by cgruber** [comment]
For those seeing this, is it happening with different versions of bazel?

**Comment by Bencodes** [comment]
We had someone run into this in our repository again this week using a single multiplexed `KotlinBuilder` instance with worker sandboxing enabled. We are using Bazel 4.1 right now.

**Comment by rockwotj** [comment]
We consistently run into this - seems to happen more when we switch branches and have java proto changes? We're also running bazel 4.1

**Comment by mgenov** [comment]
Happens in 3.6 and 4.1 on my side.

**Comment by restingbull** [comment]
@cgruber It's unlikely that the multiplex worker isn't keeping it seperated. It generates a new tmp dir for each request.

That said...

@rockwotj Try killing the multiplex worker and rerunning the build. If it passes, it's probably the worker.

**Comment by restingbull** [comment]
Also, all, what versions of kotlin are you using?

**Comment by mgenov** [comment]
KOTLIN_VERSION = "1.4.32"

**Comment by Bencodes** [comment]
We've seen this on 1.4.x and 1.5.x

**Comment by rockwotj** [comment]
1.4.32 for us too. I'll try just killing the kotlin worker next time we hit this and will report back.

**Comment by mgenov** [comment]
Killing the worker works for me.

**Comment by rockwotj** [comment]
I actually have a consistent repro for me. I'd be curious if it's the same for others.

Check out our fork of rules_kotlin (it's just a couple commits behind from head)
https://github.com/shortwave/rules_kotlin

Check out the branch `a` and build the "trivial" example (`git checkout a && cd examples/trivial && bazel build //app`)
https://github.com/shortwave/rules_kotlin/tree/a/examples/trivial

Check out the branch `b` and build the example again (`git checkout b && bazel build //app`)
https://github.com/shortwave/rules_kotlin/tree/b/examples/trivial

Compilation should fail. Note that I have ABI jars on (the same settings we have for our internal repos). I'm going to try tweaking different bazel settings and seeing if that is the cause

**Comment by rockwotj** [comment]
Killing the kotlin worker does make the build succeed

**Comment by rockwotj** [comment]
This still breaks even with abi jars off for me.

**Comment by rockwotj** [comment]
I've narrowed it down that https://github.com/bazelbuild/rules_kotlin/pull/515 is causing the issue here. By keeping the environment alive some state is being persisted that should not be. I think we should revert that change (at least for the non-multiplex-ed worker). I'm assuming the cache key that's being using in the kotlinc environment isn't playing well with the symlink forest that bazel uses? (For example they are caching based on the symlink changing instead of the actual jar).

**Comment by restingbull** [comment]
Quick poll: does this happen without multiplex workers?

**Comment by rockwotj** [comment]
Yes (my repro is without multiplex workers)

**Comment by rockwotj** [comment]
I took a peek where this flag is used in kotlinc, it seems to only [be here](https://github.com/JetBrains/kotlin/blob/master/compiler/cli/src/org/jetbrains/kotlin/cli/jvm/compiler/KotlinCoreEnvironment.kt#L505-L517
)

Which one of the things this does is [clear a zip (and presumable jar?) file cache](https://github.com/JetBrains/kotlin/blob/master/compiler/cli/src/org/jetbrains/kotlin/cli/jvm/compiler/KotlinCoreEnvironment.kt#L531)

Tracking down [that cache, it seems to do invalidation based on timestamp and filesize](https://github.com/JetBrains/intellij-community/blob/master/platform/core-impl/src/com/intellij/openapi/vfs/impl/ZipHandler.java)

I also peeked around the KotlinCoreEnvironment and I did find [another cache](https://github.com/JetBrains/kotlin/blob/master/compiler/frontend.java/src/org/jetbrains/kotlin/load/kotlin/KotlinBinaryClassCache.kt#L80) that only invalidates based on timestamps.

Presumably there are other caches hidden in places that do similar sorts of timestamp based invalidation, that doesn't play well with bazel (which I believe always writes the same timestamp to make builds be deterministic and reproducable?)

**Comment by restingbull** [comment]
Apologies, misread the bug report.

Going to approve the pr, and we'll sort out the caching + symlink fun.

**Comment by rockwotj** [comment]
It maybe worth trying setting `zip.handler.uses.crc.instead.of.timestamp`

https://github.com/JetBrains/intellij-community/blob/0f6a1386df3c27aea71cc693d8ec01cf34d349e3/platform/core-impl/src/com/intellij/openapi/vfs/impl/ZipHandlerBase.java#L32

That seems like a good thing to try ☺️

**Comment by restingbull** [comment]
Nice find! I expect I'll be doing a fair amount of testing -- but that flag
may be very important for us.

The original pr was intended to mirror the Gradle Kotlin Daemon usage. The
fact it's off in production calls that into doubt. I try to avoid using
test-only features in prod... Seems like a poor choice for stability.

As this issue eloquently proves.

**Comment by cgruber** [comment]
Closing as the PR that fixed this was merged. There is still work to do on multiplex ot fix isolation, but it's out of scope of this issue.
