### ISSUE TITLE
Annotation processor fails to process generated kotlin files

### ISSUE THREAD

**Issue by Ea87** [bazelbuild/rules_kotlin#748]
When attempting to bump our project to latest 1.6RC1, we can no longer build targets that use generated Dagger `@Module`s, written in Kotlin (our project uses kotlinpoet to generate those).

To reproduce this issue, I forked the Dagger example here: https://github.com/bazelbuild/rules_kotlin/compare/master...Ea87:repro-dagger-generated-module

this adds a simple `genrule` that generates a dagger `@Module` Kotlin class with a String provision into an srcjar; This is then used as a source for a `kt_jvm_target` that depends on dagger; Lastly the generated module is included in the `@Component` in `CoffeeApp` and the `String` is injected in `CoffeeMaker`.

When attempting to run the app with `bazel run :coffee_app`, it fails with:

```
Building coffee_lib-java.jar (3 source jars) and running annotation processors (ComponentProcessor) failed: (Exit 1): java failed: error executing command external/remotejdk11_macos_aarch64/bin/java -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 17 arguments skipped)
bazel-out/darwin_arm64-fastbuild/bin/_javac/coffee_lib/coffee_lib-java_tmp/coffee/DaggerCoffeeApp_CoffeeShop.java:8: error: cannot find symbol
import generated.GeneratedModule_ProvideStringFactory;
                ^
  symbol:   class GeneratedModule_ProvideStringFactory
  location: package generated
bazel-out/darwin_arm64-fastbuild/bin/_javac/coffee_lib/coffee_lib-java_tmp/coffee/DaggerCoffeeApp_CoffeeShop.java:46: error: cannot find symbol
    return new CoffeeMaker(DoubleCheck.lazy(provideHeaterProvider), thermosiphon(), GeneratedModule_ProvideStringFactory.provideString());
                                                                                    ^
  symbol:   variable GeneratedModule_ProvideStringFactory
  location: class DaggerCoffeeApp_CoffeeShop
```

so it seems Dagger fails to generate the `GeneratedModule_ProvideStringFactory` from the generated module; This example works with the current stable release (1.5), and fails at the commit where legacy java compilation was removed: https://github.com/bazelbuild/rules_kotlin/commit/25d4c54d379c449ef1a4e9495a183456a477fed5

When investigating this, I also noticed that interestingly if the generated `@Module` file is in Java, this does builds/run successfully and generates the dagger factory.

**Comment by arunkumar9t2** [comment]
https://github.com/bazelbuild/rules_kotlin/pull/749 fixes this
